project:
  type: book
  output-dir: docs

book:
  description: "How to carry out reproductions and replications in the social, cognitive, and behavioral sciences"
  title: "Handbook on Conducting Reproduction and Replication Studies"
  author:
    - name: "Lukas Röseler*"
      affiliation: "Münster Center for Open Science, University of Münster, Germany"
      orcid: 0000-0002-6446-1901
    - name: "Lukas Wallrich*"
      affiliation: "Birkbeck Business School, University of London, United Kingdom"
      orcid: 0000-0003-2121-5177
    - name: "Helena Hartmann"
      affiliation: "Department for Neurology and Center for Translational Neuro- and Behavioral Sciences (C-TNBS), University Hospital Essen, Germany"
      orcid: 0000-0002-1331-6683
    - name: "Luisa Altegoer"
      affiliation: "University of Münster, Institute for Translational Psychiatry"
      orcid: 0000-0001-8466-7328
    - name: "Veronica Boyce"
      affiliation: "Department of Psychology, Stanford University, United States"
      orcid: 0000-0002-8890-2775
    - name: "Sarahanne M. Field"
      affiliation: "Department of pedagogy, University of Groningen, Netherlands"
      orcid: 0000-0001-7874-1261
    - name: "Janik Goltermann"
      affiliation: "University of Münster, Institute for Translational Psychiatry, Germany"
      orcid: 0000-0003-3087-1002
    - name: "Joachim Hüffmeier"
      affiliation: "TU Dortmund University, Germany"
      orcid: 0000-0002-0490-7035
    - name: "Charlotte R. Pennington"
      affiliation: "School of Psychology, Aston University, Birmingham, United Kingdom"
      orcid: 0000-0002-5259-642X
    - name: "Merle-Marie Pittelkow"
      affiliation: "Berlin Institute of Health at Charité - Universitätsmedizin Berlin, Germany"
      orcid: 0000-0002-7877-7898
    - name: "Priya Silverstein"
      affiliation: "Center for Neuroscience and Cell Biology, University of Coimbra; Institute for Globally Distributed Open Research and Education, Portugal"
      orcid: 0000-0003-0095-339X
    - name: "Don van Ravenzwaaij"
      affiliation: "Department of psychology, University of Groningen, Netherlands"
      orcid: 0000-0002-5030-4091
    - name: "Flavio Azevedo"
      affiliation: "University of Utrecht, Department of Interdisciplinary Social Science, Netherlands"
      orcid: 0000-0001-9000-8513
  reader-mode: true
  date: "08-01-2025"
  chapters:
    - index.qmd
    - part: "Foundations"
      chapters:
        - background.qmd
        - understanding.qmd
    - part: "The Replication Process"
      chapters:
        - choosing_study.qmd
        - planning.qmd
        - execution_reproductions.qmd
        - execution_replications.qmd
        - discussion.qmd
    - part: "Advanced Topics and Applications"
      chapters:
        - publishing.qmd
        - field_specific_mri.qmd
    - part: "Conclusion and Checklist"
      chapters:
        - conclusion.qmd
    - references.qmd

  downloads: [pdf]

  appendices:
    - contributions.qmd
    - appendix_templates.qmd

  page-footer:
    center: |
       Röseler, L.\*, Wallrich, L.\*, Hartmann, H., Hüffmeier, J., Goltermann, J., Pennington, C. R., Boyce, V., Field, S. M., Pittelkow, M.-M., Silverstein, P., van Ravenzwaaij, D., Azevedo, F. (2025). Handbook on Conducting Reproduction and Replication Studies. https://forrt.org/replication_guide *shared first authorship
  favicon: images/favicon.png
  cookie-consent: false
  repo-url: https://github.com/forrtproject/replication_guide/

bibliography: references.bib

format:
  html:
    theme:
      light: [cosmo, theme.scss]
  pdf:
    documentclass: scrreprt
    classoption: ["openany", "fontsize=12pt", "parskip=half", "headings=big", "numbers=noenddot"]
    geometry: [a4paper, top=25mm, bottom=25mm, left=25mm, right=25mm]
    colorlinks: true
    link-citations: true
    include-in-header: preamble.tex
    include-before-body: cover-page.tex
    title: ""      # disables title in PDF
    author: ""     # disables authors in PDF
