---
title: "Asking for materials and data"
editor: 
  markdown: 
    wrap: 72
---

Dear \[name of author(s)\], we are conducting replication research using
some of your research. Specifically, we \[brief name of the phenomenon
and study that was replicated\]. \[We do this because … e.g., your
research addresses a very important question.\] Can you please send us
the following materials to help us design a replication as close as
possible to your original study?

-   \[list of required materials/data/code\]

-   \[list of required materials/data/code\]

-   Citation of original study: \[add citation\] We are looking forward
    to your responses! Thank you \[Your name\] Asking for comments on an
    experimental paradigm Dear \[name of authors\], We are planning a
    replication of some of your research. Specifically we are aiming to
    replicate your study \[study details and citation\]. \[we are
    interested in these findings because ...\] I’m writing to share a
    mock-up of the replication to get your feedback on whether this
    paradigm accurately captures the design of your study. Please let me
    know if you have any comments or concerns that you’d like to share.
    Here’s a link to my paradigm. Any insights you have into details
    that differ from your own study would be much appreciated. I will be
    replicating your experiment on \[planned recruitment sample\]. \[I
    know this is a deviation from the original population you tested,
    and I will note this sample decision prominently in any writeups.\]

Thanks again,\
Your name Signature

# Asking for comments on replication results

Dear \[name of author(s)\], we have conducted replication research using
some of your research. Specifically, we \[brief name of the phenomenon
and study that was replicated\]. In our study \[description of
results\]. We want to provide you with an opportunity to comment on
these findings. We plan to publish the replication report via \[paper or
publication platform, e.g., FORRT’s Replication Hub\], which asks
replication studies to be submitted alongside comments from the authors
of the original study. Your comment – if you choose to give one – will
be part of the report.

\- Citation of original study: \[add citation\]\
- Replication study:\[add link to document or attach it to the e-mail\]

We are looking forward to your responses!

Thank you\
*\[Your name\]*
