---
title: "Author Contributions"
---

| No. | Author (last name, first name) | ORCID-ID | Contribution (CRediT) | Affiliation | Country | E-Mail (should be valid for multiple years, used for communication) |
| :---- | :---- | :---- | :---- | :---- | :---- | :---- |
| 1 | Röseler, Lukas\* ✉ | [https://orcid.org/0000-0002-6446-1901](https://orcid.org/0000-0002-6446-1901) | Conceptualization, Project Administration, Writing – original draft, Writing – review & editing  | Münster Center for Open Science, University of Münster | Germany | [lukas.roeseler@uni-muenster.de](mailto:lukas.roeseler@uni-muenster.de) |
| 2 | Wallrich, Lukas \*✉ | [https://orcid.org/0000-0003-2121-5177](https://orcid.org/0000-0003-2121-5177)  | Writing – original draft, Writing – review & editing | Birkbeck Business School, University of London | United Kingdom | [l.wallrich@bbk.ac.uk](mailto:l.wallrich@bbk.ac.uk) |
| 3 | Hartmann, Helena\*✉ | [https://orcid.org/0000-0002-1331-6683](https://orcid.org/0000-0002-1331-6683)  | Writing – original draft, Writing – review & editing | Department for Neurology and Center for Translational Neuro- and Behavioral Sciences (C-TNBS), University Hospital Essen | Germany | [helena.hartmann@uk-essen.de](mailto:helena.hartmann@uk-essen.de)  |
| 4 | Azevedo, Flavio\*✉ | [https://orcid.org/0000-0001-9000-8513](https://orcid.org/0000-0001-9000-8513)  | Writing – original draft, Writing – review & editing | University of Utrecht, Department of Interdisciplinary Social Science | Netherlands | [f.a.azevedo@uu.nl](mailto:f.a.azevedo@uu.nl)  |
| 5 | Hüffmeier, Joachim | [https://orcid.org/0000-0002-0490-7035](https://orcid.org/0000-0002-0490-7035)  | Writing \- review & editing | TU Dortmund University | Germany | joachim.hueffmeier@tu-dortmund.de |
| 6 | Goltermann, Janik | [https://orcid.org/0000-0003-3087-1002](https://orcid.org/0000-0003-3087-1002)  | Writing \- review & editing | University of Münster, Institute for Translational Psychiatry | Germany | janik.goltermann@gmail.com |
| 7 | Charlotte R. Pennington | [https://orcid.org/0000-0002-5259-642X](https://orcid.org/0000-0002-5259-642X)  | Writing \- review & editing | School of Psychology, Aston University, Birmingham | United Kingdom | c.pennington@aston.ac.uk |
| 8 | Veronica Boyce | [https://orcid.org/0000-0002-8890-2775](https://orcid.org/0000-0002-8890-2775)  | Writing \- review & editing  | Department of Psychology, Stanford University | United States | vboyce@stanford.edu |
| 9 | Sarahanne M. Field | [https://orcid.org/0000-0001-7874-1261](https://orcid.org/0000-0001-7874-1261)  | Writing, review & editing | Department of pedagogy, University of Groningen | Netherlands | s.m.field@rug.nl |
| 10 | Merle-Marie Pittelkow | [https://orcid.org/0000-0002-7487-7898](https://orcid.org/0000-0002-7487-7898)  | Writing, review & editing | Berlin Institute of Health at Charité \- Universitätsmedizin Berlin | Germany | merle-marie.pittelkow@bih-charite.de |
| 11 | Don van Ravenzwaaij | [https://orcid.org/0000-0002-5030-4091](https://orcid.org/0000-0002-5030-4091)  | Writing, review & editing | Department of psychology, University of Groningen | Netherlands | d.van.ravenzwaaij@rug.nl |
| 12 | Priya Silverstein | [https://orcid.org/0000-0003-0095-339X](https://orcid.org/0000-0003-0095-339X) | Writing, review & editing | Center for Neuroscience and Cell Biology, University of Coimbra; Institute for Globally Distributed Open Research and Education | Portugal | priyasilverstein@gmail.com |
| 13 | Luisa Altegoer | [https://orcid.org/0000-0001-8466-7328](https://orcid.org/0000-0001-8466-7328)  | Writing \- review & editing | University of Münster, Institute for Translational Psychiatry | Germany | luisa.altegoer@uni-muenster.de |

# Potential Conflicts of Interest {#potential-conflicts-of-interest}

A large proportion of the authors are members of FORRT, an organization dedicated to integrating open and reproducible science into higher education. LR, LW, FA, and JG are inaugural editors of the in-development journal *Replication Research* ([https://replicationresearch.org](https://replicationresearch.org)). Besides their conviction of the value of replications, their current project’s success relies on researchers conducting reproductions and replications. LR is the managing director of an institutional open science center and proponent of repetitive research. The authors declare that they have no further potential conflicts of interest.

# Funding {#funding}

LR received funding from the University of Münster and the ‘Landesinitiative opennaccess.nrw’. LW and LR received funding from ‘UK Research and Innovation’. LW, HH, and FA received funding from the ‘Nederlandse Organisatie voor Wetenschappelijk Onderzoek’. JG received funding by ‘Innovative Medizinische Forschung’ (IMF) of the medical faculty of the University of Münster (GO122301). HH was supported by the Deutsche Forschungsgemeinschaft (DFG, German Research Foundation) \- Project-ID 422744262 \- TRR 289 (gefördert durch die Deutsche Forschungsgemeinschaft (DFG) \- Projektnummer 422744262 \- TRR 289).

# Acknowledgments {#acknowledgments}

This work is an initiative from The Framework for Open and Reproducible Research Training (FORRT; [https://forrt.org](https://forrt.org)), and all core-team authors are active members of FORRT’s Replication Hub ([https://forrt.org/replication-hub](https://forrt.org/replication-hub/)).

We thank Patrick Smela for valuable ideas on defining replication success and Abel Brodeur for suggestions about definitions and the relationship between reproducibility and replicability.
