---
title: "Communicating and Publishing"
---

## Communicating and Publishing

The final step of replication research is publishing and communicating the results. Researchers should adhere to best practices of transparency and openness promotion guidelines [TOP, @GrantEtAl2024] and to the reporting standards of their respective field [e.g., JARS standards for reporting psychology replications, @openpsychdataJARS]. For example, they should report a link to the pre-registration, analysis plan, and analysis script, share all materials and data (if possible in light of ethical and legal limitations) under an open license [see also @JanzFreese2021], and report methods and results comprehensively. Finally, in writing the report, reproduction and replication authors should be mindful of their language. Ideally, being replicated would be an honor for authors since other researchers deem their findings important but a failed replication could potentially harm the reputation of the original and increase distrust towards them among their peers. We recommend a descriptive and impersonal language. When criticizing bad documentation, no access to data, or brevity in methods replication authors should keep in mind the historical context of the original publication. For example, sharing data was much more difficult in the 1990s and not required in many areas until recently.

The journals that published the original studies are often also chosen by authors for publication in accordance with the *pottery-barn-rule* [@Srivastava2012]. However, in our experience, many journals reject replications due to their lack of novelty. We list several options for writing and publishing the report in Table 4. These are non-exclusive, that is, researchers can choose multiple of them. An overview of active journals that exclusively publish replications is in Table 5.

**Table 4**

*Reporting and communicating reproductions and replications.*

| Type | Description |
|---|---|
| FORRT Replication Database | This open and collaborative database contains thousands of replication findings and makes them visible. Anyone can enter results using a guided survey (https://t1p.de/fred_submit). |
| PubPeer | Researchers can comment on the original study and say that there is a replication attempt, describe the outcome, and provide links/references/DOIs to the replication(s). Researchers checking pubpeer.com or using the browser plug-in that automatically highlights studies for which there are comments will see your comment. |
| Manuscript (required for Preprint and Journal Article) | Manuscripts are mostly used as they are the traditional form of a research article. For judgment and decision making, there are useful examples by @Feldman2024. For reproducibility analyses the I4R Replication Report Template (https://osf.io/j2qrx) can be used. Moreover, Röseler et al. [-@RoselerEtAl2025] provide general templates for reproductions and replications. |
| Preprint | We recommend publishing a report in the form of a traditional or standardized manuscript as a preprint. This secures open access and makes the report visible, citable, and commentable. There are many preprint servers across the social sciences (e.g., PsyArxiv, SOCARXIV, SportRxiv, MediArXiv, MindRxiv, EdArXiv, AfricArXiv, or MetaArXiv). In some countries, researchers have a legal right for a secondary publication of their research (green open access). Be aware that preprints are faster in terms of publication than journal articles, but are usually not peer-reviewed. |
| Journal article | Most researchers have to “play by the rules”, that is, publish or perish [@BakkerEtAl2012; @KooleLakens2012]. While some have argued for a pottery barn rule (https://thehardestscience.com/2012/09/27/a-pottery-barn-rule-for-scientific-journals/) where journals that published the original finding have to publish respective replication attempts, many journals are not (yet) interested in replications. Notable exceptions are listed in the appendix. This is why journals dedicated to replications have emerged (see Table 5). Moreover, researchers can submit their preprint to a PCI community (see https://peercommunityin.org/current-pcis/), which is a preprint peer-review service. Several journals are PCI-friendly, which means that they publish articles recommended by the respective PCI. 
Many institutions and libraries recommend adding a CC-BY disclaimer on journal submissions that give the researchers the right to use the accepted manuscript as they like or choosing Diamond Open Access journals that are defined by no fees for publishing and reading research. |


**Table 5**

*Active journals dedicated to reproductions and replications.*

| Journal name | Commercial status | Owners | Disciplines | Article types | Website |
|---|---|---|---|---|---|
| Journal of Comments and Replications in Economics | Non-commercial, diamond OA | ZBW | Economics | Replications, Reproductions and comments research | https://jcr-econ.org |
| Replication Research | Non-commercial, diamond OA | Münster Center for Open Science and FORRT | Multidisciplinary | Reproductions, Replications, Conceptual articles | https://replicationresearch.org  |
| Journal of Open Psychology Data | Commercial, Gold OA (APCs: 450 pounds) | Ubiquity Press | Psychology | Reproductions (only as Registered Reports) | https://openpsychologydata.metajnl.com  |
| Journal of Robustness Reports | Non-commercial, diamond OA | SciPost | Multidisciplinary | At least two independent reproductions are required, limited to 500 words | https://scipost.org/JRobustRep  |
| Rescience C | Non-commercial, diamond OA | Olivia Guest, Benoît Girard, Konrad Hinsen, Nicolas P. Rougier | Multidisciplinary | Reproductions | https://rescience.github.io  |
| Journal of Management Scientific Reports | Commercial (subscription based) | Sage | Management | Replications, reproductions, related methods | https://smgmt.org/jomsr/ |
| Journal of Reproducibility in Neuroscience | Non-commercial, diamond OA | Center of Trial and Error | Neuroscience | Replications, Comments, Reviews, conceptual articles | https://jrn.trialanderror.org |
| Rescience X | Non-commercial, diamond OA | Etienne B. Roesch | Multidisciplinary | Replications (Experiments) | http://rescience.org/x  |
| AIS Transactions on Replication Research | Non-commercial, diamond OA | Association for Information Systems (?) | Information Systems | Exact, Methodological, Conceptual Replications | https://aisel.aisnet.org/trr/  |
