on:
  workflow_dispatch:
  push:
    branches: [main]

name: Quarto Render to docs

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - uses: r-lib/actions/setup-r@v2

      - run: Rscript -e 'install.packages(c("dplyr", "knitr", "rmarkdown"))'

      - name: Render site into docs/
        run: quarto render --output-dir docs

      - name: Commit and push rendered docs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Update rendered docs [skip ci]" || echo "No changes to commit"
          git push
